version: '3.3'
services:
  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: ${MYSQL_PW}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PW}
    ports:
      - 3306:3306
    volumes:
      - mysql-db:/var/lib/mysql
  postgres:
    image: postgres
    restart: always
    environment:
      # postgres builtin user = postgres
      # default db = postgres
      POSTGRES_PASSWORD: ${POSTGRES_PW}
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    volumes:
      - postgres-db:/var/lib/postgresql/data
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PW}
    ports:
      - 27017:27017
    volumes:
      - mongo-db:/data/db
# Names our volume
volumes:
  mysql-db:
  postgres-db:
  mongo-db:
